apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Exposes it externally on the node IP
  selector:
    app: kube-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # access frontend via NodeIP:30080
