apiVersion: v1
kind: Service
metadata:
  name: verification-service
spec:
  type: ClusterIP
  selector:
    app: verification
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001


# Explanation:

# Other pods in the cluster (like your frontend if deployed here) can access 
# Verification via http://verification-service:3001