apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
  labels:
    app: verification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
        - name: verification-container
          image: kube-credentialsdocker-verification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            # Point verification service to the internal Issuance service
            - name: ISSUANCE_API_URL
              value: "http://issuance-service:5001"



# Explanation:

# ISSUANCE_API_URL points to the Kubernetes Service name (issuance-service) and its port (5001).

# Now, Verification pods can call Issuance pods internally, without exposing them to the internet.